    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: r-lib/actions/setup-r@v2
          - uses: r-lib/actions/setup-r-dependencies@v2
            with:
              extra-packages: |<
                any::testthat
                any::rmarkdown
          - uses: education/autograding@v1