name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing pak and building lockfile
        id: install
        shell: sudo Rscript {0}
        run: |
          cat("::set-output name=os-version::", sessionInfo()$running, "\n", sep = "")
          cat("::set-output name=r-version::", if (grepl("development", rv <- R.Version()$version.string)) as.character(getRversion()) else rv, "\n", sep = "")
          cat("::set-output name=lib-dir::", Sys.getenv("R_LIBS_USER"))
          dir.create(Sys.getenv("R_LIBS_USER"), showWarnings=FALSE, recursive=TRUE)
          install.packages("pak", repos="https://r-lib.github.io/p/pak/devel/", lib=Sys.getenv("R_LIBS_USER"))
          .libPaths(Sys.getenv("R_LIBS_USER"))
          dir.create(".github", showWarnings=FALSE)
          pak::lockfile_create(c("any::sessioninfo", "testthat", "rmarkdown"), lockfile=".github/pkg.lock")
      - name: Restore R package cache
        uses: actions/cache@v2
        with: 
          path: |
            ${{ steps.install.outputs.lib-dir }}/*
            !${{ steps.install.outputs.lib-dir }}/pak
          key: ${{ steps.install.outputs.os-version }}-${{ steps.install.outputs.r-version }}-${{ hashFiles('.github/pkg.lock') }}
      - name: Install dependencies
        shell: sudo Rscript {0}
        run: |
          cat(.libPaths)
          pak::lockfile_install(".github/pkg.lock")
      - uses: education/autograding@v1
        continue-on-error: true