name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing pak and building lockfile
        shell: sudo Rscript {0}
        run: |
          install.packages("pak", repos="https://r-lib.github.io/p/pak/stable/")
          dir.create(".github", showWarnings=FALSE)
          pak::lockfile_create(c("any::sessioninfo", "testthat", "rmarkdown"), lockfile=".github/pkg.lock")
          writeLines(readLines(".github/pkg.lock"))
      - uses: education/autograding@v1